server:
  port : 5000

spring:
  application:
    name: product-backend

similar:
  products:
    api:
      base-url: ${SIMILAR_PRODUCTS_API_BASE_URL:http://localhost:3001}

#logging:
#  level:
#    root: WARN
  
#    com.julian.product_backend.infrastructure.adapter.out.api: INFO
